--- #YAML:1.0
name: CGI-Echo
version: 1.04
author:
  - Ron Savage <ron@savage.net.au>
abstract: Echo form data to test form design.
license: artistic
requires:
  Carp: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides: {}
generated_by: Module::Build version 0.24
